/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateTopicArgs } from "./CreateTopicArgs";
import { UpdateTopicArgs } from "./UpdateTopicArgs";
import { DeleteTopicArgs } from "./DeleteTopicArgs";
import { TopicFindManyArgs } from "./TopicFindManyArgs";
import { TopicFindUniqueArgs } from "./TopicFindUniqueArgs";
import { Topic } from "./Topic";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { TopicService } from "../topic.service";

@graphql.Resolver(() => Topic)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class TopicResolverBase {
  constructor(
    protected readonly service: TopicService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "any",
  })
  async _topicsMeta(
    @graphql.Args() args: TopicFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Topic])
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "any",
  })
  async topics(@graphql.Args() args: TopicFindManyArgs): Promise<Topic[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Topic, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "own",
  })
  async topic(
    @graphql.Args() args: TopicFindUniqueArgs
  ): Promise<Topic | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Topic)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "create",
    possession: "any",
  })
  async createTopic(@graphql.Args() args: CreateTopicArgs): Promise<Topic> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Topic)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "update",
    possession: "any",
  })
  async updateTopic(
    @graphql.Args() args: UpdateTopicArgs
  ): Promise<Topic | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Topic)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "delete",
    possession: "any",
  })
  async deleteTopic(
    @graphql.Args() args: DeleteTopicArgs
  ): Promise<Topic | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Topic])
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "any",
  })
  async dependOn(
    @graphql.Parent() parent: Topic,
    @graphql.Args() args: TopicFindManyArgs
  ): Promise<Topic[]> {
    const results = await this.service.findDependOn(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Topic])
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "any",
  })
  async dependOnMe(
    @graphql.Parent() parent: Topic,
    @graphql.Args() args: TopicFindManyArgs
  ): Promise<Topic[]> {
    const results = await this.service.findDependOnMe(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async knownUsers(
    @graphql.Parent() parent: Topic,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findKnownUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
