/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateTopicArgs } from "./CreateTopicArgs";
import { UpdateTopicArgs } from "./UpdateTopicArgs";
import { DeleteTopicArgs } from "./DeleteTopicArgs";
import { TopicFindManyArgs } from "./TopicFindManyArgs";
import { TopicFindUniqueArgs } from "./TopicFindUniqueArgs";
import { Topic } from "./Topic";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { TopicService } from "../topic.service";
import { Public } from "src/auth/public";

@graphql.Resolver(() => Topic)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class TopicResolverBase {
  constructor(
    protected readonly service: TopicService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "any",
  })
  async _topicsMeta(
    @graphql.Args() args: TopicFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  // @graphql.Query(() => [Topic])
  // @nestAccessControl.UseRoles({
  //   resource: "Topic",
  //   action: "read",
  //   possession: "any",
  // })
  // @Public()
  // async topics(
  //   @graphql.Args() args: TopicFindManyArgs,
  //   @gqlUserRoles.UserRoles() userRoles: string[]
  // ): Promise<Topic[]> {
  //   const permission = this.rolesBuilder.permission({
  //     role: userRoles,
  //     action: "read",
  //     possession: "any",
  //     resource: "Topic",
  //   });
  //   const results = await this.service.findMany(args);
  //   return results.map((result) => permission.filter(result));
  // }

  @graphql.Query(() => Topic, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "own",
  })
  async topic(
    @graphql.Args() args: TopicFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Topic | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Topic",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Topic)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "create",
    possession: "any",
  })
  async createTopic(
    @graphql.Args() args: CreateTopicArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Topic> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Topic",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Topic"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Topic)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "update",
    possession: "any",
  })
  async updateTopic(
    @graphql.Args() args: UpdateTopicArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Topic | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Topic",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Topic"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Topic)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "delete",
    possession: "any",
  })
  async deleteTopic(
    @graphql.Args() args: DeleteTopicArgs
  ): Promise<Topic | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Topic])
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "any",
  })
  async dependOn(
    @graphql.Parent() parent: Topic,
    @graphql.Args() args: TopicFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Topic[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Topic",
    });
    const results = await this.service.findDependOn(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [Topic])
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "any",
  })
  async dependOnMe(
    @graphql.Parent() parent: Topic,
    @graphql.Args() args: TopicFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Topic[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Topic",
    });
    const results = await this.service.findDependOnMe(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }

  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "any",
  })
  async knownUsers(
    @graphql.Parent() parent: Topic,
    @graphql.Args() args: UserFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const results = await this.service.findKnownUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results.map((result) => permission.filter(result));
  }
}
