/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TopicService } from "../topic.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TopicCreateInput } from "./TopicCreateInput";
import { TopicWhereInput } from "./TopicWhereInput";
import { TopicWhereUniqueInput } from "./TopicWhereUniqueInput";
import { TopicFindManyArgs } from "./TopicFindManyArgs";
import { TopicUpdateInput } from "./TopicUpdateInput";
import { Topic } from "./Topic";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TopicControllerBase {
  constructor(
    protected readonly service: TopicService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Topic })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: TopicCreateInput): Promise<Topic> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Topic] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(TopicFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Topic[]> {
    const args = plainToClass(TopicFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Topic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: TopicWhereUniqueInput
  ): Promise<Topic | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Topic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: TopicWhereUniqueInput,
    @common.Body() data: TopicUpdateInput
  ): Promise<Topic | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Topic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: TopicWhereUniqueInput
  ): Promise<Topic | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/dependOn")
  @ApiNestedQuery(TopicFindManyArgs)
  async findManyDependOn(
    @common.Req() request: Request,
    @common.Param() params: TopicWhereUniqueInput
  ): Promise<Topic[]> {
    const query = plainToClass(TopicFindManyArgs, request.query);
    const results = await this.service.findDependOn(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/dependOn")
  async connectDependOn(
    @common.Param() params: TopicWhereUniqueInput,
    @common.Body() body: TopicWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dependOn: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/dependOn")
  async updateDependOn(
    @common.Param() params: TopicWhereUniqueInput,
    @common.Body() body: TopicWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dependOn: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/dependOn")
  async disconnectDependOn(
    @common.Param() params: TopicWhereUniqueInput,
    @common.Body() body: TopicWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dependOn: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/dependOnMe")
  @ApiNestedQuery(TopicFindManyArgs)
  async findManyDependOnMe(
    @common.Req() request: Request,
    @common.Param() params: TopicWhereUniqueInput
  ): Promise<Topic[]> {
    const query = plainToClass(TopicFindManyArgs, request.query);
    const results = await this.service.findDependOnMe(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/dependOnMe")
  async connectDependOnMe(
    @common.Param() params: TopicWhereUniqueInput,
    @common.Body() body: TopicWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dependOnMe: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/dependOnMe")
  async updateDependOnMe(
    @common.Param() params: TopicWhereUniqueInput,
    @common.Body() body: TopicWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dependOnMe: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/dependOnMe")
  async disconnectDependOnMe(
    @common.Param() params: TopicWhereUniqueInput,
    @common.Body() body: TopicWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dependOnMe: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/knownUsers")
  @ApiNestedQuery(UserFindManyArgs)
  async findManyKnownUsers(
    @common.Req() request: Request,
    @common.Param() params: TopicWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findKnownUsers(params.id, {
      ...query,
      select: {
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/knownUsers")
  async connectKnownUsers(
    @common.Param() params: TopicWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      knownUsers: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/knownUsers")
  async updateKnownUsers(
    @common.Param() params: TopicWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      knownUsers: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "Topic",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/knownUsers")
  async disconnectKnownUsers(
    @common.Param() params: TopicWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      knownUsers: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
